import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const GENERATED_NOTE =
  "> Auto-generated by `pnpm codegen:docs`. Do not edit manually.\n\n";

interface PackageDocEntry {
  symbol: string;
  kind: string;
  subpath?: string;
}

interface PackageDoc {
  name: string;
  version: string;
  entries: PackageDocEntry[];
}

const PACKAGE_EXPORTS: PackageDoc[] = [
  {
    name: "@agent-ready/schema",
    version: "0.3.0-rc",
    entries: [
      { symbol: "defineAction", kind: "function" },
      { symbol: "defineObservation", kind: "function" },
      { symbol: "createSchemaAdapter", kind: "function" },
      { symbol: "detectZodMajorVersion", kind: "function" },
      { symbol: "toJsonSchema", kind: "function" },
      { symbol: "validateAgentInput", kind: "function" },
      { symbol: "AgentHandle", kind: "type" },
      { symbol: "AgentResult", kind: "type" }
    ]
  },
  {
    name: "@agent-ready/runtime",
    version: "0.3.0-rc",
    entries: [
      { symbol: "createAgentRuntime", kind: "function" },
      { symbol: "invokeAction", kind: "method" },
      { symbol: "readObservation", kind: "method" },
      { symbol: "subscribeObservation", kind: "method" },
      { symbol: "getCatalog", kind: "method" }
    ]
  },
  {
    name: "@agent-ready/react",
    version: "0.3.0-rc",
    entries: [
      { symbol: "AgentReadyProvider", kind: "component" },
      { symbol: "useAgentSurface", kind: "hook" },
      { symbol: "useAgentAction(handle, action, handler)", kind: "hook" },
      { symbol: "useAgentObservation(handle, definition, selector, options?)", kind: "hook" },
      { symbol: "useAgentCatalog", kind: "hook" }
    ]
  },
  {
    name: "@agent-ready/react/rsc",
    version: "0.3.0-rc",
    entries: [
      { symbol: "declareAgentManifest", kind: "function" },
      { symbol: "serializeAgentManifests", kind: "function" }
    ]
  },
  {
    name: "@agent-ready/mcp",
    version: "0.3.0-rc",
    entries: [
      { symbol: "createMcpHandlers", kind: "function" },
      { symbol: "createMcpSseServer", kind: "function", subpath: "./sse" }
    ]
  },
  {
    name: "@agent-ready/observability",
    version: "0.3.0-rc",
    entries: [
      { symbol: "attachRuntimeListener", kind: "function" },
      { symbol: "attachOtelTracing", kind: "function" },
      { symbol: "attachOtelTracingAuto", kind: "function", subpath: "./node" }
    ]
  },
  {
    name: "@agent-ready/bridge",
    version: "0.3.0-rc",
    entries: [{ symbol: "createBridgeServer", kind: "function" }]
  },
  {
    name: "@agent-ready/testing",
    version: "0.3.0-rc",
    entries: [
      { symbol: "createTestRuntime", kind: "function" },
      { symbol: "createMockAgent", kind: "function" }
    ]
  }
];

function renderPackageTable(): string {
  const rows = PACKAGE_EXPORTS.map(
    (pkg) => `| ${pkg.name} | ${pkg.version} | ${pkg.entries.length} |`
  );
  return [
    "| Package | Version | Exports |",
    "|---------|---------|---------|",
    ...rows
  ].join("\n");
}

function renderPackageDetails(): string {
  return PACKAGE_EXPORTS.map((pkg) => {
    const rows = pkg.entries.map((entry) => {
      const path = entry.subpath ? `\`${entry.subpath}\`` : "`.`";
      return `| \`${entry.symbol}\` | ${entry.kind} | ${path} |`;
    });
    return [
      `## ${pkg.name}`,
      "",
      "| Symbol | Kind | Entry |",
      "|--------|------|-------|",
      ...rows,
      ""
    ].join("\n");
  }).join("\n");
}

export function codegenDocs(outputPath: string) {
  mkdirSync(dirname(outputPath), { recursive: true });

  const indexMd = [
    GENERATED_NOTE,
    "# Agent Ready SDK — API Index",
    "",
    "Release: **0.3.0-rc**",
    "",
    renderPackageTable(),
    "",
    "See [packages.md](./packages.md) for symbol-level reference.",
    "",
    "Canonical contract: [sdk-api.md](../sdk-api.md).",
    ""
  ].join("\n");

  const packagesMd = [
    GENERATED_NOTE,
    "# Agent Ready SDK — Package Exports",
    "",
    renderPackageDetails()
  ].join("\n");

  writeFileSync(outputPath, indexMd);
  writeFileSync(join(dirname(outputPath), "packages.md"), packagesMd);
  console.log("Wrote", outputPath);
  console.log("Wrote", join(dirname(outputPath), "packages.md"));
}
